### ISSUE TITLE
Damping

### ISSUE THREAD

**Issue by garygreen** [Lucifier129/pull-element#6]
Hey, great library I love how it's focused on just doing one thing and doing it well.

Though I have a question about the 'damping' option and what it should be used for. Could you give more examples on it's use case and why the default is 1.6 ? Is this some kind of "sensitivity" option or something?

**Comment by Lucifier129** [comment]
`damping` is used to simulate the spring effect in a naive way

![image](https://user-images.githubusercontent.com/6636455/59812919-44a06e00-9342-11e9-9ddc-ecf33e851ff8.png)

Let's try it in [pull-element playground](https://lucifier129.github.io/pull-element/demo/build/#playground)

Said we start touching in here

![01](https://user-images.githubusercontent.com/6636455/59813063-ba0c3e80-9342-11e9-8ad0-3f9677a5726e.png)

What if the `damping` value is ***1***

![02](https://user-images.githubusercontent.com/6636455/59813103-d90ad080-9342-11e9-88b8-f7364d9a6c7f.png)

It shows that the moving distance is almost equal to the distance of the user's touch-move. It may be too sensitive, sometimes boring.

What if the `damping` value is ***1.6***

![03](https://user-images.githubusercontent.com/6636455/59813409-e8d6e480-9343-11e9-8f83-179d844429e6.png)

It looks like there exists a reaction force interacting with the user.

What if the `damping` value is ***4***

![04](https://user-images.githubusercontent.com/6636455/59813609-b2e63000-9344-11e9-87f0-28bf653fc653.png)

Oh, too sluggish! It's hard to move an element. the user got a bad experience.

The default value ***1.6*** is selected by my testing, we can change the value when it doesn't make sense.

**Comment by garygreen** [comment]
Woah thanks for the great explanation. So it's almost a bit like "friction" so the touch isn't a 1/1 but feels like there is some kind of resistance to it. Hope I understood that correct, thanks once again 👍
