### ISSUE TITLE
Swipeable-Tabs: Exclude element from target

### ISSUE THREAD

**Issue by fleischsalod** [Lucifier129/pull-element#7]
Hi @Lucifier129 ,

this is kinda related to https://github.com/Lucifier129/pull-element/issues/5
I would like to be able to exclude a specific element inside a target. The reason is the following: In the content of one tab, i wanted to add a list of elements that can be scrolled horizontally.

I only see the possibility to use both technologies (the swipeable tabs and the horizontal-scroll) by excluding the `div`, which should be scrolled horizontally, from the target (probably by passing a `className` or something like that).

Would love to have this feature shipped with your already great library! 
Is it planned to add this feature?

**Comment by Lucifier129** [comment]
Hi 

The [options.trigger](https://github.com/Lucifier129/pull-element#optionstrigger-selectorelement) is the thing to include, now it supports multiple elements as the trigger 

[usage](https://github.com/Lucifier129/pull-element/blob/master/demo/src/page/CustomTrigger.js#L62) and [demo](https://lucifier129.github.io/pull-element/demo/build/#custom-trigger)

Touch the trigger to pull.

![image](https://user-images.githubusercontent.com/6636455/63491138-0281dd00-c4e9-11e9-9222-650e50dc2770.png)

I hope this can help to solve your problem

**Comment by fleischsalod** [comment]
Hi @Lucifier129 ,

Sorry for this late response.
Unfortunately, your solution was not applicable in my case. But i found a solution, which might be interesting for others.
You can exclude any element, that is nested (doesn't matter how deep) in the targeted element, by adding a touchMove-`EventListener` and call `stopPropagation` on it:
`<div onTouchMove={e => e.stopPropagation()}>Exclude from Swiping</div>`
Hope this can help anybody facing a similar problem.

Anyway, @Lucifier129 best thanks for your help, i love your library and it works perfectly now!
